#!/usr/bin/env bash
#Install nginx on your web-01 server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School
#As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get -y install nginx
sudo echo -e '<html>\n<head>\n</head>\n<body>\nHolberton School\n</body>\n</html>' > /var/www/html/index.html
sudo /etc/init.d/nginx start
