#!/usr/bin/env bash
#The redirection must be a “301 Moved Permanently”
#You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
#Using what you did with 1-install_nginx_web_server, write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get update
sudo apt-get -y install nginx
echo -e 'Holberton School' > /var/www/html/index.html
sed -i '43i location /redirect_me{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=EgBJmlPo8Xw permanent;\n}\n' /etc/nginx/sites-available/default
service nginx start
