#!/usr/bin/env bash
#The redirection must be a “301 Moved Permanently”
#You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
#Using what you did with 1-install_nginx_web_server, write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task
sudo apt-get update
sudo apt-get -y install nginx
echo -e '<html>\n<head>\n</head>\n<body>\nHolberton School\n</body>\n</html>' > /var/www/html/index.html
sudo sed -i 'rewrite ^/redirect_me$ https://www.youtube.com/watch?v=EgBJmlPo8Xw permanent;' /etc/nginx/sites-enabled/default
service nginx start
