#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#The name of the custom HTTP header must be X-Served-By
#The value of the custom HTTP header must be the hostname of the server Nginx is running on
#Write 0-custom_http_response-header so that it configures a brand new Ubuntu machine to the requirements asked in this task
#Ignore SC2154 for shellcheck

sudo apt-get update
sudo apt-get -y install nginx
echo -e 'Holberton School' > /var/www/html/index.html
sed -i '43i location /redirect_me{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=EgBJmlPo8Xw permanent;\n}\n' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '46i error_page 404 /404.html;\nlocation = /404.html {\ninternal;\n}\n' /etc/nginx/sites-available/default
sed -i '22i add_header X-Served-By $HOSTNAME;\n' /etc/nginx/nginx.conf
service nginx start
