#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*
echo -e "frontend haproxynode\n\tbind *:80" >> /etc/haproxy/haproxy.cfg
echo -e "\tmode http\n\tdefault_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo -e "backend web-backend\n\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 1075-web-01 35.237.41.190:80 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 1075-web-02 3.90.183.111:80 check\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
