#!/usr/bin/env bash
# Nginx must not be running, and listening on port 80 of all the server’s active IPv4 IPs
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
