#!/usr/bin/env bash
#This script manage manage_my_proces
ARGV0=$0
ARGC=$#
if [ "$ARGC" -ne "1" ]
then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit
fi 
if [ "$1" == "start" ]
then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
    id="$(cat /var/run/my_process.pid)"
    kill -17 "$id"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
    id="$(cat /var/run/my_process.pid)"
    kill -17 "$id"
    rm /var/run/my_process.pid
    ./manage_my_process & 
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
