#!/usr/bin/env bash
# This script displays numbers from  1 to 100
# multiples of 3 and 5 prints FizzBuzz
# multiples of 3 Fizz and multiples of 5 FizzBuzz
i="1"
while [ $i -le "100" ]
do
    if [ $((i%3)) -eq "0" ] && [ $((i%5)) -eq "0" ]
    then
        echo "FizzBuzz"
    elif [ $((i%3)) -eq "0" ]
    then
        echo "Fizz"
    elif [ $((i%5)) -eq "0" ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
: $((++i))
done
