#!/usr/bin/env bash
# This script prints 10 times Holberton School using while loop
# the 4th time prints bad luck instead, and the 8th prints good luck
i="1"
while [ $i -le 10 ]
do 
if [ "$i" -eq "4" ]
then
    echo "bad luck"
elif [ "$i" -eq "8" ]
then
    echo "good luck"
else
    echo "Holberton School"
fi
: $((++i))
done
