#!/usr/bin/env bash
# This script prints numbers from 1 to 20
# the 4th bad luck from China, the 9th bad luck from Japan
# the 17th bad luck from Italy
i="1"
while [ $i -le 20 ]
do 
echo "$i"
if [ "$i" -eq "4" ]
then
    echo "bad luck from China"
elif [ "$i" -eq "9" ]
then
    echo "bad luck from Japan"
elif [ "$i" -eq "17" ]
then
    echo "bad luck from Italy"
fi
: $((++i))
done
