#!/usr/bin/env bash
# This script prints numbers from 1 to 20
# the 4th bad luck from China, the 9th bad luck from Japan
# the 17th bad luck from Italy
i="1"
while [ $i -le 20 ]
do 
echo "$i"
case $i in
    4) echo "bad luck from China"
    ;;
    9) echo "bad luck from Japan"
    ;;
    17) echo "bad luck from Italy"
    ;;
esac
: $((++i))
done
