#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements.
cat /etc/hosts > auxiliar
while read -r IP host
do
    if [ "$host" == "localhost" ]
    then
        echo "127.0.0.2 localhost" > /etc/hosts
    else
        echo "$IP"" ""$host" >> /etc/hosts
    fi
done < auxiliar
echo "8.8.8.8 facebook.com" >> /etc/hosts
rm auxiliar
